-- MySQL Script generated by MySQL Workbench
-- Sun Jul 31 19:11:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

CREATE TABLE IF NOT EXISTS `cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `ativo` INT NOT NULL DEFAULT 1 COMMENT '0 = inativo\n1 = ativo',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecnico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecnico` ;

CREATE TABLE IF NOT EXISTS `tecnico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `servico` ;

CREATE TABLE IF NOT EXISTS `servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `referencia` VARCHAR(20) NOT NULL,
  `ativo` INT NOT NULL DEFAULT 1 COMMENT '0 = inativo\n1 = ativo',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `os` ;

CREATE TABLE IF NOT EXISTS `os` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente` INT NOT NULL,
  `tecnico` INT NOT NULL,
  `servico` INT NOT NULL,
  `cancelada` INT NOT NULL DEFAULT 0 COMMENT '0 = nao\n1 = sim',
  PRIMARY KEY (`id`, `cliente`, `tecnico`, `servico`),
  INDEX `fk_os_cliente_idx` (`cliente` ASC) VISIBLE,
  INDEX `fk_os_tecnicos1_idx` (`tecnico` ASC) VISIBLE,
  INDEX `fk_os_produto1_idx` (`servico` ASC) VISIBLE,
  CONSTRAINT `fk_os_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_tecnicos1`
    FOREIGN KEY (`tecnico`)
    REFERENCES `tecnico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_produto1`
    FOREIGN KEY (`servico`)
    REFERENCES `servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peca` ;

CREATE TABLE IF NOT EXISTS `peca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `referencia` VARCHAR(20) NULL,
  `ativo` INT NOT NULL DEFAULT 1 COMMENT '0 = inativo\n1 = ativo',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `os_peca` ;

CREATE TABLE IF NOT EXISTS `os_peca` (
  `id` INT NOT NULL,
  `peca` INT NOT NULL,
  PRIMARY KEY (`id`, `peca`),
  INDEX `fk_os_has_peca_peca1_idx` (`peca` ASC) VISIBLE,
  INDEX `fk_os_has_peca_os1_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_os_has_peca_os1`
    FOREIGN KEY (`id`)
    REFERENCES `os` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_has_peca_peca1`
    FOREIGN KEY (`peca`)
    REFERENCES `peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
